### ISSUE TITLE
Language Packs category is for display language extensions

### ISSUE THREAD

**Issue by gregvanl** [Avinm/VSCode-Ion-Format-Support#1]
The "Language Packs" VS Code extension category is to designate display language (German, Bulgarian) extensions and not for general programming language extensions.

```json
"categories": [
        "Language Packs"
    ],
```

Please remove "Language Packs" from categories in package.json and use the "Programming Languages" instead.

![image](https://user-images.githubusercontent.com/12818376/42248857-a88baed2-7edc-11e8-8dc9-bff4dc60656b.png)

**Comment by Avinm** [comment]
Fixed in [8e3fcac](https://github.com/Avinm/VSCode-Ion-Format-Support/commit/8e3fcac4a45e8022763542a38b7f30fcb5597304)

**Comment by gregvanl** [comment]
Thanks for jumping on this!
