### ISSUE TITLE
formatting is all wrong

### ISSUE THREAD

**Issue by archaistvolts** [Avinm/VSCode-Ion-Format-Support#2]
Not sure if there are any other settings affect formatting.  
I'm on windows 10.  I have format on save turned on.  After installing this extension, this:

```c
import libc {printf}

func main(argc: int, argv: char**): int {
    printf("Hello, world!\n");
    return 0;
}
```
is being turned into this:
```c
importlibc{
  printf
}
funcmain(argc:int,
argv:char**):int{
  printf( "Hello, world!\n");return0;}
```
It looks like many spaces and some newlines are being removed.  

Can formatting be turned off just for this extension?  

Any idea what is going wrong?

**Comment by Avinm** [comment]
Hi,

This extension should be activated only for ion files. Your code looks like it is in golang and therefore you need to change the language in vscode to golang instead of ion

Regards,
Avin
________________________________

**Comment by archaistvolts** [comment]
Thank you.  Changing the language mode to Go at the bottom right seems to have worked only for the one file and the current session.  Other open ion files are remain in Ion language mode.  And if I close vscode and reopen, all .ion files revert back to Ion language mode.  

This is a nuisance if I have to make the change for every new .ion file I open.  

Is this what you had in mind or is there another way to "activate only for ion files"?

**Comment by Avinm** [comment]
I'm sorry but why do you have Go code in ion files? I have registered the extension to get activated for ion files.

Regards,
Avin
________________________________

**Comment by archaistvolts** [comment]
There is only ion code (from [pervognsen/bitwise/ ion compiler](https://github.com/pervognsen/bitwise/tree/master/ion).  There is no Go code in the hello world example above... it is only ion code adapted from [ion/test2/main.ion](https://github.com/pervognsen/bitwise/blob/master/ion/test2/main.ion).  

Isn't this extension meant for this ion or is there another?

**Comment by Avinm** [comment]
No, this extension is meant for Amazon Ion: http://amzn.github.io/ion-docs/
